// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which provider and model AI features use. Saved in the settings store; keys stay in the keychain.
 */
export type AiConfig = { 
/**
 * "gemini" (also when empty), "anthropic" or "openai" (any OpenAI-compatible server).
 */
provider: string, 
/**
 * Empty = the provider's default model.
 */
model: string, 
/**
 * "openai" only: server base URL, e.g. http://localhost:11434/v1. Empty = api.openai.com. A custom URL
 * needs no key (local servers).
 */
base_url: string, };
