// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error sent to the frontend: a stable code plus a beginner-friendly message.
 */
export type AppError = { code: string, message: string, };
