// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the "askpass" event; answer it with the `askpass_reply` command.
 */
export type AskpassPrompt = { id: number, 
/**
 * git's or ssh's prompt, e.g. "Password for 'https://x@github.com': ".
 */
prompt: string, };
