// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlameHunk } from "./BlameHunk";

export type Blame = { 
/**
 * The file's text at the blamed commit; None when binary or over 1 MB (no hunks then).
 */
text: string | null, hunks: Array<BlameHunk>, };
