// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lines `start..start + lines` (1-based) of the blamed file came from commit `oid`.
 */
export type BlameHunk = { oid: string, start: number, lines: number, subject: string, author: string, time: number, };
