// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

export type CommitDetails = { oid: string, parents: Array<string>, 
/**
 * "Name <email>".
 */
author: string, 
/**
 * Author time, seconds since the epoch.
 */
time: number, committer: string, message: string, 
/**
 * Changes against the first parent (the empty tree for a root commit).
 */
files: Array<FileChange>, 
/**
 * Already part of the current branch (merge or cherry-pick would do nothing).
 */
in_head: boolean, };
