// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shown in the browser: the user types `user_code` at `verification_uri`.
 */
export type DeviceCode = { device_code: string, user_code: string, verification_uri: string, 
/**
 * Seconds between polls.
 */
interval: number, 
/**
 * Seconds until the code expires.
 */
expires_in: number, };
