// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Editors = { 
/**
 * Display names of the editors found, in a fixed order. On Windows the last is `OTHER`.
 */
found: Array<string>, 
/**
 * The last one used; None = the OS default app.
 */
chosen: string | null, };
