// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commit that changed a file, for the file history list.
 */
export type FileCommit = { oid: string, 
/**
 * The file's path in this commit (an older name before a rename).
 */
path: string, subject: string, author: string, time: number, };
