// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileChange = { path: string, 
/**
 * Source path of a rename/copy.
 */
orig_path: string | null, 
/**
 * Porcelain letter: M A D R C T, "?" for untracked, two letters (e.g. "UU") for conflicts.
 */
kind: string, };
