// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repo the signed-in user can clone.
 */
export type GhRepo = { 
/**
 * "owner/name".
 */
full_name: string, 
/**
 * HTTPS URL; askpass answers it with the token.
 */
clone_url: string, private: boolean, description: string | null, };
