// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's global git setup: commit identity and where git keeps HTTPS sign-ins.
 */
export type GitSetup = { name: string | null, email: string | null, 
/**
 * `credential.helper`, e.g. "manager" (Git Credential Manager). None = git asks every time.
 */
helper: string | null, 
/**
 * What `set_global` would set as the helper on this OS; None where there's no safe default.
 */
helper_default: string | null, };
