// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphRow = { oid: string, 
/**
 * Lane of this commit's dot.
 */
col: number, 
/**
 * Lines from the previous row's center at lane `.0` to this row's center at lane `.1`.
 */
edges: Array<[number, number]>, summary: string, author: string, 
/**
 * Author time, seconds since the epoch.
 */
time: number, 
/**
 * Short names of the branches, remote branches and tags pointing here.
 */
refs: Array<string>, head: boolean, };
