// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the history view shows.
 */
export type GraphOpts = { 
/**
 * Every branch and tag; false = only what HEAD reaches.
 */
all: boolean, 
/**
 * Remote branches (as walk starts and as labels).
 */
remotes: boolean, 
/**
 * Commit date order; false = ancestor order (keeps each branch's commits together).
 */
by_date: boolean, };
