// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphRow } from "./GraphRow";

export type GraphPage = { total: number, 
/**
 * Widest lane count of the whole graph.
 */
lanes: number, rows: Array<GraphRow>, };
