// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Lfs = { 
/**
 * `git lfs` runs (git-lfs is on PATH).
 */
installed: boolean, 
/**
 * Tracked patterns as `git lfs track` lists them (spaces show as `[[:space:]]`).
 */
patterns: Array<string>, };
