// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the op log.
 */
export type OpEntry = { 
/**
 * Unix time in ms, also the backup ref name.
 */
id: string, 
/**
 * "discard", "amend", "merge", "cherry-pick", "abort <op>", "delete branch", "delete tag",
 * "drop stash", "pull", "delete remote branch", or "undo <op>" for the undo of an op.
 */
op: string, 
/**
 * HEAD (or `ref_name`) before the op; None = the ref didn't exist.
 */
head: string | null, 
/**
 * HEAD (or `ref_name`) after the op, when the op moved it; None = deleted. Undo moves it back.
 */
new_head: string | null, 
/**
 * The ref `head`/`new_head` belong to, when not HEAD (e.g. "refs/heads/feature").
 */
ref_name: string | null, paths: Array<string>, 
/**
 * Working-tree snapshot of `paths` taken before the op. Undo restores it.
 */
backup: string | null, 
/**
 * For "undo": the id of the undone entry.
 */
undoes: string | null, };
