// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the op log.
 */
export type OpEntry = { 
/**
 * Unix time in ms, also the backup ref name.
 */
id: string, 
/**
 * "discard", "amend" or "undo".
 */
op: string, 
/**
 * HEAD before the op.
 */
head: string | null, 
/**
 * HEAD after the op, when the op moved it. Undo moves it back.
 */
new_head: string | null, paths: Array<string>, 
/**
 * Working-tree snapshot of `paths` taken before the op. Undo restores it.
 */
backup: string | null, 
/**
 * For "undo": the id of the undone entry.
 */
undoes: string | null, };
