// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A commit of `base..HEAD`, for the interactive rebase list.
 */
export type RebaseCommit = { oid: string, message: string, author: string, time: bigint, };
