// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseAction } from "./RebaseAction";

export type RebaseStep = { oid: string, action: RebaseAction, 
/**
 * New message for the resulting commit (for squash: the combined one); None keeps git's.
 */
message: string | null, };
