// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefItem = { 
/**
 * Short name ("main", "origin/main", "v1.0"), or the message for a stash.
 */
name: string, oid: string, 
/**
 * Upstream short name of a local branch.
 */
upstream: string | null, 
/**
 * Commits ahead of / behind the upstream.
 */
ahead: number, behind: number, };
