// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefItem } from "./RefItem";

export type Refs = { 
/**
 * Current branch; None when HEAD is detached or unborn.
 */
head: string | null, local: Array<RefItem>, remote: Array<RefItem>, tags: Array<RefItem>, 
/**
 * Newest first (stash@{0} first).
 */
stashes: Array<RefItem>, };
