// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoInfo = { 
/**
 * Absolute path of the working tree root.
 */
path: string, name: string, 
/**
 * Current branch, or None when HEAD is detached or unborn.
 */
branch: string | null, };
