// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How `reset_to` treats the index and the working tree.
 */
export type ResetMode = "Soft" | "Mixed" | "Keep" | "Hard";
