// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

export type Status = { 
/**
 * Current branch, or None when HEAD is detached.
 */
branch: string | null, staged: Array<FileChange>, 
/**
 * Unstaged changes plus untracked files (kind "?").
 */
unstaged: Array<FileChange>, conflicted: Array<FileChange>, };
