// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Terminals = { 
/**
 * `BUILT_IN` first, then the terminal apps installed here.
 */
found: Array<string>, 
/**
 * The one the Terminal button opens.
 */
chosen: string, };
